### ISSUE TITLE
Integration checklist

### ISSUE THREAD

**Issue by baolean** [baolean/EthBMC#1]
- [ ] Using `setUp()` result to initialize contract(s) state
- [ ] Implement `CREATE` and constructor support
- [ ] Preserve storage changes made by *all* (not just the "victim") contracts
- [ ] Add "symbolic storage" mode
- [ ] Decode function names in counterexample
- [ ] Fix loop detection
- [x]  Detect failed assets in solc >= 0.8
