### ISSUE TITLE
Integration Checklist

### ISSUE THREAD

**Issue by baolean** [baolean/EthBMC#2]
- [x]  [Using setUp() result to initialize contract(s) state](https://github.com/baolean/EthBMC/commit/d1638c43bda514b2e4ae5680fdbf1ed94ee2ab6b)
- [x]  [Symbolically execute functions starting with prove](https://github.com/baolean/EthBMC/commit/d1638c43bda514b2e4ae5680fdbf1ed94ee2ab6b)
- [x]  [Detect failed assets in solc >= 0.8](https://github.com/baolean/EthBMC/commit/7c59b5902178465363a8749d420944e5f7e143a0)
- [x] [Decode function names in counterexamples](https://github.com/baolean/EthBMC/commit/cc3cde59dad17a48cbc66613813d536e0c748d9a)
- [x]  [Detect failed asserts in solc < 0.8 
](https://github.com/baolean/EthBMC/commit/888df8b76378e57ee2f8c954a55376770a3aa308)
- [x]  [Detect forge's asserts 
](https://github.com/baolean/EthBMC/commit/82ba6a37ac705ce0cbf69abc9001642cddcac0ca)
- [x] [Set `block.timestamp` and `block.number` values in `geth` based on the attack counterexample](https://github.com/baolean/EthBMC/commit/460ae046a00d24c3ff798bea80a625d48bfaeafe)
- [x] [Make solver and its timeout configurable](https://github.com/baolean/EthBMC/commit/94648d36580380369dbea21e8434400becd43c6f)
- [x] [Fix `view`/`pure` functions analysis](https://github.com/baolean/EthBMC/commit/f94d6f5e6a28f7df566f5b50a716c571fc1345b0)
- [ ] [WIP] Detect reverts w/ specific error messages **(Done for "Overflow")**
- [ ] [WIP] Add "symbolic storage" mode
- [ ] Fix loop detection
- [ ] Consider using `ethers` instead of `geth` for validation
- [ ] Support `Foundry` and `hevm` cheatcodes, e.g., `warp`
- [ ] Implement CREATE and constructor support
- [ ] Investigate false positives w/o concrete validation
